### ISSUE TITLE
[Request] Add a search plugin

### ISSUE THREAD

**Issue by Daenyth** [47degrees/sbt-microsites#503]
One thing that I think would make the scala documentation situation globally improved is for the common doc tools to provide search over the doc pages.

The `mkdocs` tool for example does this, and it makes discovery *a lot* better. It uses https://lunrjs.com/ to implement, but I'm sure there's other tools if that's hard to integrate for some reason.

**Comment by sloshy** [comment]
Progress update: after getting the build working again, I've got working search index generation. I'm playing around with the generated html/css layouts to see if I can make it look half-decent before I throw it up there.
<img width="666" alt="Screen Shot 2021-01-21 at 6 18 43 PM" src="https://user-images.githubusercontent.com/427237/105428763-afe4ad00-5c15-11eb-8ad4-19a1c5828ee6.png">
