### ISSUE TITLE
Make call to action button on landing page lead to "Documentation" instead of "View on GitHub"

### ISSUE THREAD

**Issue by olafurpg** [47degrees/sbt-microsites#508]
I have seen a lot of Microsite websites with an action button on the landing page that points to "View on GitHub". For example  https://pureconfig.github.io/

<img width="1189" alt="Screenshot 2020-10-01 at 14 30 42" src="https://user-images.githubusercontent.com/1408093/94812293-d4aedd80-03f6-11eb-8df0-1de0f67ebaa5.png">

I think it would be nice if the call to action button pointed to "Documentation" instead. Feel free to close this issue, just wanted to report this since I have several times browsed a repo on GitHub, opened the website link, accidentally clicked on "View on GitHub" to bring me back to the GitHub repo.

**Comment by sloshy** [comment]
Hello @olafurpg o/ I've picked this up and submitted a PR as linked above. Do let me know if you have any thoughts or concerns!
