### ISSUE TITLE
Fix the build

### ISSUE THREAD

**Issue by sloshy** [47degrees/sbt-microsites#531]
In both #530 and #529, both of which have relatively inconsequential changes (especially #530) the build appears to be broken. `sbt microsite/makeMicrosite` seems to be failing and the root cause needs to be found out.

So far from what I can tell, it is failing because the file `microsite/target/scala-2.12/resource_managed/main/jekyll/img/light_navbar_brand.png` is empty.

**Comment by sloshy** [comment]
The source of the issue, and resolution, had something to do with the way the old code behaved. I'm not entirely sure what it was, but, rewriting the JAR export code to use `java.nio.file.FileSystem` instead, everything works as you would expect. The resulting code I think is a bit smaller and easier to grok, and it also works on my machine as well as GitHub Actions.

What **doesn't** work now, is, Jekyll appears to not be installed. I will resume investigating this issue in the future, unless someone else wants to pick it up.

**Comment by calvellido** [comment]
Just commenting without much context, but bear in mind that Jekyll is a system requirement for the project. Nothing in the process is gonna fetch it or install it.

Also, we have had cases where the Jekyll version is not ^4.0.0 and the process will think none is installed.
