### ISSUE TITLE
Documentation Page / Website not working

### ISSUE THREAD

**Issue by yadavan88** [47degrees/sbt-microsites#727]
Hi,
I was trying to explore microsite and found out that the site is not loading. Screenshot attached below.
![image](https://user-images.githubusercontent.com/9131956/207950796-c1629e65-10f6-4fd7-b1e2-d1287e2b8eda.png)

**Comment by fedefernandez** [comment]
@yadavan88, thanks for the heads-up. I've updated the site to a previous version for now.

**Comment by fedefernandez** [comment]
Not sure what happened. Potentially, the connection while the build was committing the microsite failed. I've regenerated the site manually.

**Comment by yadavan88** [comment]
Hi @fedefernandez Thanks for looking into it. I am still seeing the same symbols in this link https://47degrees.github.io/sbt-microsites/
Probably, it is still getting generated?

**Comment by fedefernandez** [comment]
The build fails when using github4s for site publication
